version: '3'
services:
#    laravel.test:
#        image: '${TEST_TAG}'
#        ports:
#            - '80:80'
#        networks:
#            - test
#        depends_on:
#            - mysql
#            - selenium
    mysql:
        image: 'mysql:5.7'
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: test
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: testing
            MYSQL_PASSWORD: password
        ports:
            - '33006:3306'
        networks:
            - test
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
            interval: 10s
            retries: 3
            timeout: 5s
#    selenium:
#        image: 'selenium/standalone-chrome'
#        volumes:
#            - '/dev/shm:/dev/shm'
#        networks:
#            - test
networks:
    test:
        driver: bridge
