version: '3'
services:
    laravel.test:
        image: '${TEST_TAG}'
        hostname: laravel.test
        ports:
            - '80:80'
        networks:
            - test
        depends_on:
            - mysql
            - selenium
    mysql:
        image: 'mysql:8'
        environment:
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_USER: test
            MYSQL_DATABASE: testing
            MYSQL_PASSWORD: password
        networks:
            - test
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-prootpw"]
            interval: 10s
            retries: 3
            timeout: 5s
    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - test
networks:
    test:
        driver: bridge
