name: Build -> Test -> Push
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          target: production
          tags: aaronkunert/laravel-app:testing
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true

  test:

    runs-on: ubuntu

    container:
      image: aaronkunert/laravel-app:testing
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      options: --hostname laravel.test

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      selenium:
        image: selenium/standalone-chrome
        volumes:
          - '/dev/shm:/dev/shm'

    steps:

      - name: Copy env
        run: cp ./docker/testing/.env.ci .env

      - name: Prepare Application
        run: php artisan key:generate

      - name: Unit and Feature Tests
        run: php artisan test --stop-on-failure --testsuite All

      - name: Browser Tests
        run: php artisan dusk --stop-on-failure


  push:
    runs-on: ubuntu

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set latest tag
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: aaronkunert/laravel-app:testing
          dst: aaronkunert/laravel-app:latest

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Echo Tag Name
        run: echo ${{ steps.tag.outputs.result }}

      - name: Set specific tag
        if: ${{ steps.tag.outputs.result }}
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: aaronkunert/laravel-app:latest
          dst: aaronkunert/laravel-app:${{steps.tag.outputs.result}}
