on: push
name: CI

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      selenium:
        image: selenium/standalone-chrome
        volumes:
          - '/dev/shm:/dev/shm'

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Install node dependencies
        run: |
          npm ci
          npm run build

      - name: Prepare Laravel Application
        run: |
          rm .env.dusk.local
          cp .env.ci .env
          php artisan key:generate
          cat .env

      - name: Run Testsuite
        run: vendor/bin/phpunit --stop-on-failure --testsuite All

      - name: Start Server
        run: php artisan serve &

      - name: Run Browser Tests
        run:  |
          php artisan config:cache
          php artisan dusk --stop-on-failure
